### ISSUE TITLE
Field order should replicate existing core UX

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/image-shortcake#50]
We should replicate core's field order and presentation format as much as possible:

![image](https://cloud.githubusercontent.com/assets/36432/8677845/478e53f6-2a06-11e5-9fbd-c1153937dc84.png)

**Comment by danielbachhuber** [comment]
We might also want to tighten up the fields a bit with some custom CSS.

**Comment by goldenapples** [comment]
FWIW, the order of fields in our theme is being filtered [here](https://github.com/fusioneng/fusion-theme/blob/master/inc/integrations/class-image-shortcake.php#L51-71). Removing that filter would leave fields in the order they are in the insert media modal. Since the order in the Image Shortcake dialog is what editorial requested, I suspect that reordering fields in the core UI for the theme is more desirable.

**Comment by danielbachhuber** [comment]
> Since the order in the Image Shortcake dialog is what editorial requested

Meaning... the current order they now want changed is what was originally requested?

**Comment by goldenapples** [comment]
> Meaning... the current order they now want changed is what was originally requested?

um... yup. I think the current issue has more to do with the fact that the order is not consistent between the two experiences where those fields are visible, than that they actually prefer the order of the fields in the Insert Media experience.

**Comment by danielbachhuber** [comment]
Ok. Let's just handle this within the theme then. Plugin is fine as it is.
